name: Deploy to EC2

on:
    push:
      branches:
        - main
    workflow_run:
      workflows: ["tests"]
      types:
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check if stack exists
        run: |
          stack_status=$(aws cloudformation describe-stacks --stack-name FastApiCICDstack101 --query 'Stacks[0].StackStatus' --output text --region ${{ secrets.AWS_REGION }} 2>/dev/null)
          if [[ -z $stack_status ]]; then
            create_update_action="create"
            if [[ $stack_status == "ROLLBACK_COMPLETE" ]]; then
              create_update_action="update"
            fi
          else
            create_update_action="update"
          fi
        
      - name: Deploy CloudFormation stack
        run: |
          if [[ $create_update_action == "create" ]]; then
            aws cloudformation create-stack --stack-name FastApiCICDstack101 --template-url ${{ secrets.CLOUD_FORMATION_TEMPLATE }}
          else
            aws cloudformation update-stack --stack-name FastApiCICDstack101 --template-url ${{ secrets.CLOUD_FORMATION_TEMPLATE }}
          fi
          #https://raw.githubusercontent.com/nnitiwe-dev/fastapi-cicd-demo/main/config/aws/cloudformation-template.yml

      - name: Get Instance URL
        run: |
          # Run your script to extract the URL of the running FastAPI application
          ./config/aws/get_instance_url.sh

